services:
  controller:
    build:
      context: .
      dockerfile: services/controller/Dockerfile
    image: tom_controller
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - docker.env
    ports:
      - "8000:8000"
#    restart: always
    volumes:
      - ./inventory:/app/inventory
      - ./tom_controller_config.yaml:/app/tom_controller_config.yaml
    command:
      - ".venv/bin/fastapi"
      - "run"
      - "src/tom_controller/main.py"
      - "--workers"
      - "1"

  worker:
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    image: tom_worker
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - docker.env
    volumes:
      - ./inventory:/app/inventory

  redis:
#    image: redis:7.4-alpine3.21
    build: ./docker/redis
    ports:
      - "6380:6380"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  vault:
    image: hashicorp/vault:1.20.2
    ports:
      - '8200:8200'
    volumes:
      - vault-data:/vault/data
      - vault-logs:/vault/logs
#      - ./vault-config:/vault/config

    environment:
      VAULT_DEV: "true"   # remove for prod
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"  # remove for prod
      VAULT_DEV_LISTEN_ADDRESS: "vault:8200"
      VAULT_ADDR: "http://vault:8200"

    cap_add:
      - IPC_LOCK
    command: ["vault", "server", "-dev"]  # remove -dev for prod

volumes:
  vault-data:
    driver: local
  vault-logs:
    driver: local

