[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "click<=8.1.2",
    "mike>=2.1.3",
    "mkdocs>=1.6.1",
    "mkdocs-cinder>=1.2.0",
    "mkdocs-material>=9.7.0",
    "mkdocs-mermaid2-plugin>=1.2.3",
]
